// <auto-generated />
namespace ArkBot.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Vote_ServerKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Vote_ServerKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201704281757362_Vote_ServerKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
